      SUBROUTINE ERRWRT(STR)

C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C
C SUBPROGRAM:    ERRWRT
C   PRGMMR: J. ATOR          ORG: NP12       DATE: 2009-04-21
C
C ABSTRACT: THIS SUBROUTINE WRITES A GIVEN ERROR OR OTHER DIAGNOSTIC
C   MESSAGE FROM THE NCEP BUFRLIB (I.E. BUFR ARCHIVE LIBRARY) TO THE
C   DECODER LOG.  IT IS INCLUDED WITHIN THE DECODER UT LIBRARY, AND
C   AS SUCH IT WILL OVERRIDE THE BUFRLIB SUBROUTINE OF THE SAME NAME
C   FOR ALL OF THE NCEP DECODERS WHICH ARE LINKED TO THE UT LIBRARY.
C
C PROGRAM HISTORY LOG:
C 2009-04-21  J. ATOR    -- ORIGINAL AUTHOR
C
C USAGE:    CALL ERRWRT (STR)
C   INPUT ARGUMENT LIST:
C     STR      - CHARACTER*(*): ERROR MESSAGE TO BE PRINTED TO
C                DECODER LOG
C
C ATTRIBUTES:
C   LANGUAGE: FORTRAN 77
C   MACHINE:  PORTABLE TO ALL PLATFORMS
C
C$$$

      CHARACTER*(*) STR

      CALL ST_LSTR ( STR, LSTR, IERSTR )
      IF ( LSTR .GE. 100 ) THEN
         CALL DC_WLOG ( 0, ' ', 1, STR, IERWLG )
      ELSE IF ( LSTR .GT. 0 ) THEN
         CALL DC_WLOG ( 0, 'DC', 2, STR, IERWLG )
      ENDIF

      RETURN
      END
