      BLOCK DATA FONT16
C
C          DATA SET PHCHARAC   AT LEVEL 003 AS OF 05/11/93
C$$$  SUBPROGRAM DOCUMENTATION BLOCK
C                .      .    .                                       .
C SUBPROGRAM:    FONT16      SYMBOL DEFS (FONT16) FOR PRTITL
C   PRGMMR: SHIMOMURA        ORG: NMC41       DATE:95-10-03
C
C ABSTRACT: FONT16 -- CHARACTER SET_16 DEFINITION;
C   IN RASTER-GRAPHICS, BIT-MAPPED FORM;
C     LOOK16 OR  CD16=(20X6) 1 HORIZONTAL BAR
C
C PROGRAM HISTORY LOG:
C   ??-??-??  ORIGINAL AUTHOR: GLORIA DENT (BEFORE 1974)
C   93-05-11  LILLY UPDATES DOCBLOCK.
C   93-06-03  HENRICHSEN
C   93-10-26  SHIMOMURA -- CONVERTING FROM IBM-ASM INTO CRAY-FORTRAN
C                          BLOCK DATA;
C                          CHANGED THE ORDER FROM EBCDIC TO ASCII
C                          SORTING SEQ.
C
C USAGE:   linkage-edit the member=PHCHARAC 
C   INPUT ARGUMENT LIST:
C
C     ... THIS MEMBER IS NOT CALLED; THE OBJECT CODE IS LINKAGE-EDITED
C
C REMARKS: 
C     ... THE IBM-ASM VERSION IS LIKE A BLOCK DATA SUBPROGRAM 
C     ...                     WHICH DEFINED COMMON /CHARAC/
C     ... THIS CRAY-FORTRAN VERSION DEFINES ONLY ONE OF THE 50 FONTS,
C     ...    NAMELY, FONT16  OR  CD16=(20X6) 1 HORIZONTAL BAR
C     ... COMMON /FONS_16/ KHTITLE, NUMSET,NCHS_16,NWPC_16,KIXTB_16,
C     ...1                 KDF_16
C             
C
C ATTRIBUTES:
C   LANGUAGE: CRAY FORTRAN
C   MACHINE:  CRAY4
C
C$$$
C          DATA SET PHCHARAC   AT LEVEL 001 AS OF 04/17/93
C          DATA SET PHCHARAC   AT LEVEL 001 AS OF 06/05/89
C          DATA SET PHCHARAC   AT LEVEL 006 AS OF 10/03/85
C ...         TITLE 'COMMON /CHARAC/DEFSYM -- SYMBOL DEFS FOR PRTITL'
C ...         CHARAC   CSECT
C
C   THIS CHARH SET IS PHCHARAC FOUND ON DPH.PAN.SOURCE.A
C   UPDATED 03 OCT 1985 BY PETER HENRICHSEN TO :
C    ADD NOAA DUCK AND MEDIUM DUCK TO CD10.
C    ADD 24 DOT DUCKLING TO CD1.
C    ADD ALPHABET, ' ', '.' AND '/' TO CD19.
C   MODIFIED BY GLORIA AND PETER TO ADD TROPICAL STORM SYMBOL IN CD10
C   01 OCT 1982.
C
C
C      LOOK16 OR  CD16=(20X6) 1 HORIZONTAL BAR
C
       COMMON /FONS_16/ KHTITLE_16,NUMSET_16,NCHS_16,NWPC_16,KIXTB_16,
     1                  KDF_16
       CHARACTER*8    KHTITLE_16
       INTEGER*8    NUMSET_16
       INTEGER*8    NWPC_16
       INTEGER*8    NCHS_16

       CHARACTER*8    KIXTB_16(8)

       INTEGER*8    KDF_16(3,1)


C      LOOK16 OR  CD16=(20X6) 1 HORIZONTAL BAR
C ...  COMMON /FONS_16/ KHTITLE_16,NUMSET_16,NCHS_16,NWPC_16,KIXTB_16,KDF_16
       DATA    KHTITLE_16 / "HORZ_BAR" /
       DATA    NUMSET_16  / 16 /
       DATA    NWPC_16    /  3 /        !... WORDS PER CHARACTER
       DATA    NCHS_16    /  1 /        !... NO. OF CHAR DEFS IN SET_16
C                     ...   COL 12345678
       DATA         KIXTB_16 / "A       ",
     2                         "        ",
     3                         "        ",
     4                         "        ",
     5                         "        ",
     6                         "        ",
     7                         "        ",
     8                         "        " /

C      LOOK16 OR  CD16=(20X6) 1 HORIZONTAL BAR
       DATA     KDF_16     /
C ...  CD16     DC    CL1'A'
     A X'FFFFF0FFFFF0FFFF',X'F0FFFFF0FFFFF0FF',X'FFF0000000000000' /
     
       END
